#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="1.28"
URL="https://releases.wikimedia.org/mediawiki/${VERSION}/mediawiki-${VERSION}.0.tar.gz"

dl $URL /usr/local/src

