#!/bin/sh -ex

DB_NAME=mediawiki
DB_USER=mediawiki
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey123

SRC=/usr/local/src
WEBROOT=/var/www/mediawiki

tar xf $SRC/mediawiki-*.tar.gz -C $SRC
rm -rf $SRC/mediawiki-*.tar.gz
mv $SRC/mediawiki-* $WEBROOT
chown -R www-data:www-data $WEBROOT

a2enmod headers
a2dissite 000-default
a2ensite mediawiki
a2enmod headers
a2enmod rewrite

# start services
service mysql start
service apache2 start

php $WEBROOT/maintenance/install.php "TurnKey+MediaWiki" "$ADMIN_NAME" \
    --dbname=$DB_NAME \
    --dbserver="localhost" \
    --installdbuser=root \
    --installdbpass=$MYSQL_PASS \
    --dbuser=$DB_USER \
    --dbpass=$DB_PASS \
    --scriptpath="" \
    --server="" \
    --lang=en \
    --pass=$ADMIN_PASS

# create welcome page
echo "Welcome to MediaWiki.<br>
Consult the [http://meta.wikimedia.org/wiki/Help:Contents User's Guide]
for information on using the wiki software.<br><br>
== Getting started ==
* Log in as '''Admin''' and start your wiki!
* [https://www.turnkeylinux.org/mediawiki TurnKey Linux MediaWiki appliance release notes]
* [http://www.mediawiki.org/wiki/Manual:Configuration_settings MediaWiki Configuration settings list]
* [http://www.mediawiki.org/wiki/Manual:FAQ MediaWiki FAQ]
* [http://lists.wikimedia.org/mailman/listinfo/mediawiki-announce MediaWiki release mailing list]
" | php $WEBROOT/maintenance/edit.php -u $ADMIN_NAME --no-rc -b Main_Page

# update default logos to tkl ones
mv /usr/local/src/*.png $WEBROOT/resources/assets/
chown www-data:www-data $WEBROOT/resources/assets/*.png
sed -i "\|'1x' =>| s|change-your-logo.svg|change-your-logo-tkl.png|" $WEBROOT/LocalSettings.php
sed -i "\|'icon' =>| s|change-your-logo-icon.svg|change-your-logo-icon-tkl.png|" $WEBROOT/LocalSettings.php

# stop services
service mysql stop
service apache2 stop
