#!/bin/bash -e
# regenerate mediawiki secret key and mysql password

. /etc/default/inithooks

updateconf() {
    CONF=/var/www/mediawiki/LocalSettings.php
    sed -i "s/^$1 \(.*\)/$1 = \"$2\";/" $CONF
}

updateconf '\$wgSecretKey' $(mcookie)$(mcookie)

PASSWORD=$(mcookie)
updateconf '\$wgDBpassword' $PASSWORD
$INITHOOKS_PATH/bin/mysqlconf.py --user=mediawiki --pass="$PASSWORD"

